version: "3.9"
services:
  core-backend:
    build:
      context: .
    container_name: core-backend
    ports:
      - "8085:8085"
    environment:
      SPRING_REDIS_HOST: 172.31.250.176
      SPRING_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 172.31.249.132:9092
    restart: on-failure
