services:
  nginx:
    image: nginx:latest
    container_name: reverse-proxy
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d   # récupère le fichier pour le mettre dans le conteneur en read-only
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/:/var/log/nginx
    ports:
      - "80:80"
      - "1883:1883"
    restart: unless-stopped