version: "3.9"

services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - "1883:1883"     # MQTT plain
      - "9001:9001"     # MQTT over WebSocket 
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  telemetry-backend:
    build: .
    container_name: telemetry-backend
    depends_on:
      - mqtt-broker
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "172.31.249.132:9092"  # IP de la VM Kafka
      MQTT_BROKER_URL: "tcp://mqtt-broker:1883"       # le nom du service MQTT ici
    restart: unless-stopped
